(define (subsets s)
  (if (null? s)
      (list '())
      (let ((rest (subsets (cdr s)))
            (first (car s)))
        (append rest (map (lambda (curr-set)
                            (cons first curr-set))
                       rest)))))
